name: Windows Powershell

on:
  workflow_dispatch:

jobs:
  mkfile:
    strategy:
      matrix:
        win: [windows-latest, windows-2025, self-hosted]
    runs-on: ${{ matrix.win }}
    steps:
      - run: |
          $currentDirectory = Get-Location
          $filePath = Join-Path -Path $currentDirectory -ChildPath "NewFile.txt"
          New-Item -Path $filePath -ItemType File -Force
          icacls $filePath
