name: Test Libpcap Installation

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Enable Multi-Arch Support
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update

      - name: Install Both Architectures
        run: |
          sudo apt install -y libpcap0.8-dev:amd64 libpcap0.8-dev:i386

      - name: Verify Installation
        run: dpkg -l | grep libpcap
